@startuml

title 예매해라(reserve)

Client --> Screening : 예매해라(reserve)
Screening --> Movie : 가격을 계산해라(calculateMovieFee)
Movie --> DiscountPolicy : 할인될 가격을 계산해라 (calculateDiscountAmount)
DiscountPolicy --> DiscountCondition : 할인 여부를 판별해라(isSatisfiedBy)
Screening --> Reservation : create

@enduml